# load json2aRgs for parameter parsing
library(json2aRgs)

# load Catflow package
library(Catflow)

# get the call parameters for the tool
params <- get_parameters()

# check if a toolname was set in env
toolname <- tolower(Sys.getenv("TOOL_RUN"))

# default tool make geometry -> future decission for a default tool
if (toolname == "") {
    toolname <- "make_geometry"
}

# Switch for the different tools available in this package
if (toolname == "make_geometry") {
    # output file is always saved to /out/
    params$out.file <- "/out/geometry.geo"

    # run function make.geometry() with params as input parameters
    pdf("/out/geometry.pdf")
    output <- make.geometry(params, plottitle = "Model Geometry")
    dev.off()

    # save output of make.geometry() for use in other tools
    saveRDS(output, file = "/out/geom.Rds")
} else if (toolname == "write_facmat") {
    # load geometry generated by the tool make_geometry and attach
    geom <- readRDS(params$geometry)
    attach(geom)

    # multipliers for scaling saturated hydraulic conductivity
    write.facmat(output.file = "/out/ksmult.dat")

    # multipliers for scaling saturated water content / porosity
    write.facmat(output.file = "/out/thsmult.dat")

    # write initial conditions for hydraulic conductivity
    if (params$write_soilhyd_ini) {
       write.facmat(output.file = "/out/soilhyd.ini",
                    headr = paste("PSI ", 0, 1, length(eta), length(xsi), 1))
    }

    # write soiltype identifiers
    if (params$write_soil_types) {
        write.facmat(output.file = "/out/soils.bod",
                     headr = paste("BODEN", length(eta), length(xsi), 1),
                     fac = matrix(c(rep(1, ceiling(length(eta) / 2)),
                                    rep(2, floor(length(eta) / 2))),
                                  nrow = length(eta), ncol = length(xsi)))
    }
} else if (toolname == "write_precip") {
    # output file is always saved to /out/
    params$output.file <- "/out/rain.dat"

    # write precipitation data with params as input
    do.call(write.precip, params)

    # plot rainfall data
    pdf("/out/raindat.pdf")
    output <- plot(params$raindat, t = "s", xlab = "time", ylab = "precipitation")
    dev.off()
} else if (toolname == "write_climate") {
    # output file is always saved to /out/
    params$output.file <- "/out/clima.dat"

    # write climate data with params as input
    do.call(write.climate, params)
} else if (toolname == "write_printout") {
    # output file is always saved to /out/
    params$output.file <- "/out/printout.prt"

    # write printout times
    do.call(write.printout, params)
} else if (toolname == "write_surface_pob") {
    # load geometry generated by the tool make_geometry and attach
    geom <- readRDS(params$geometry)
    attach(geom)

    # drop geometry from params (unused in write.surface.pob)
    params$geometry <- NULL

    # output file is always saved to /out/
    params$output.file <- "/out/surface.pob"

    # write surface attributes
    do.call(write.surface.pob, params)
} else if (toolname == "write_control") {
    # output file is always called catflow.in
    params$output.file <- "run_cat.in"

    # project.path is always /out/CATFLOW
    params$project.path <- "/out/CATFLOW"

    # create the project folder and set permissions
    system("mkdir /out/CATFLOW")
    system("chmod 777 /out/CATFLOW")

    # build slope.in.list
    params$slope.in.list <- list(
        slope1 = list(
            geo.file = "test.geo",
            soil.file = "soils.bod",
            ks.fac = "ksmult.dat",
            ths.fac = "thsmult.dat",
            macro.file = "profil.mak",
            cv.file = "cont_vol.cv",
            ini.file = "soilhyd.ini",
            print.file = "printout.prt",
            surf.file = "surface.pob",
            bc.file = "boundary.rb"
            ))

    # write project controll file
    do.call(write.control, params)

    # write main control file
    write.CATFLOW.IN(params$output.file, project.path = params$project.path)
} else {
    # in any other case, the tool was invalid or not configured
    f <- file("/out/error.log")
    writeLines(paste("[", Sys.time(), "] Either no TOOL_RUN environment variable available, or '", toolname, "' is not valid.\n", sep=""), con=f)
    close(f)
}