library(Catflow)

# load the parameters parser
source("get_parameters.R")

# get the call parameters for the tool
params <- get_parameters()

# check if a toolname was set in env
toolname <- tolower(Sys.getenv("TOOL_RUN"))

# default tool make geometry -> future decission for a default tool
if (toolname == "") {
    toolname <- "make_geometry"
}

# Switch for the different tools available in this package
if (toolname == "make_geometry") {
    # run function make.geometry() with params as input parameters
    pdf("/out/geometry.pdf")
    output <- make.geometry(params, plottitle = "Model Geometry")
    dev.off()

    # save output of make.geometry() for use in other tools
    saveRDS(output, file = "/out/geom.Rds")
} else if (toolname == "write_facmat") {
    # load geometry generated by the tool make_geometry and attach
    geom <- readRDS(params$geometry)
    attach(geom)

    # multipliers for scaling saturated hydraulic conductivity
    write.facmat(output.file = "/out/ksmult.dat")

    # multipliers for scaling saturated water content / porosity
    write.facmat(output.file = "/out/thsmult.dat")

    # write initial conditions for hydraulic conductivity
    if (params$write_soilhyd_ini) {
       write.facmat(output.file = "/out/soilhyd.ini",
                    headr = paste("PSI ", 0, 1, length(eta), length(xsi), 1))
    }

    # write soiltype identifiers
    if (params$write_soil_types) {
        write.facmat(output.file = "/out/soils.bod",
                     headr = paste("BODEN", length(eta), length(xsi), 1),
                     fac = matrix(c(rep(1, ceiling(length(eta) / 2)),
                                    rep(2, floor(length(eta) / 2))),
                                  nrow = length(eta), ncol = length(xsi)))
    }
} else if (toolname == "write_precip") {
    # write precipitation data with params as input
    do.call(write.precip, params)

    # plot rainfall data
    pdf("/out/raindat.pdf")
    output <- plot(params$raindat, t = "s", xlab = "time", ylab = "precipitation")
    dev.off()
} else if (toolname == "write_climate") {
   # write climate data with params as input
   do.call(write.climate, params)
} else {
    # in any other case, the tool was invalid or not configured
    f <- file("/out/error.log")
    writeLines(paste("[", Sys.time(), "] Either no TOOL_RUN environment variable available, or '", toolname, "' is not valid.\n", sep=""), con=f)
    close(f)
}